version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: sshCloud
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - app-network

  sshcloudserver:
      build: .
      depends_on:
        - mysql
      ports:
        - "8080:8080"
      networks:
        - app-network

networks:
  app-network:
    driver: bridge