version: '3.8'

services:
  mysql:
    container_name: SSH-Cloud-DB-Server
    image: mysql:latest
    environment:
      MYSQL_DATABASE: sshCloud
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    restart: unless-stopped