name: AndroidBuild

on:
  pull_request :
    branches : [ main ]

jobs:
  build:
    runs-on : windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: check if Android app files are changed
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD &gt; files.txt
          while (IFS= read -r file)
          do
            echo $file
            if [[ $file != Android/* ]]; then
              echo "This modified file is not under the 'db' folder."
              echo "::set-output name=run_job::false"
              break
            else
              echo "::set-output name=run_job::true"
            fi
          done &lt; files.txt

      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        working-directory: ./Android
        run : ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: dsTemplate.apk
          path: Android/app/build/outputs/apk/debug/app-debug.apk
